"""Initial Schema

Revision ID: 1be94bebf9c4
Revises: 
Create Date: 2026-02-23 23:15:19.381148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1be94bebf9c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_plantilla',
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('area_construida', sa.Float(), nullable=False),
    sa.Column('area_privada', sa.Float(), nullable=False),
    sa.Column('habitaciones', sa.Integer(), nullable=False),
    sa.Column('banos', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('rol', sa.Enum('super_admin', 'admin', 'asesor', 'comprador', name='rolusuario'), nullable=False),
    sa.Column('nombre_completo', sa.String(), nullable=False),
    sa.Column('entidad_financiera', sa.String(), nullable=True),
    sa.Column('estado_credito', sa.Enum('preaprobado', 'aprobado', 'definitivo', name='estadocredito'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('proyectos',
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('ubicacion', sa.String(), nullable=False),
    sa.Column('es_vis', sa.Boolean(), nullable=True),
    sa.Column('zonas_sociales', sa.JSON(), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('torres',
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('numero_pisos', sa.Integer(), nullable=False),
    sa.Column('numero_aptos', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pisos',
    sa.Column('numero_nivel', sa.Integer(), nullable=False),
    sa.Column('cantidad_aptos', sa.Integer(), nullable=False),
    sa.Column('torre_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['torre_id'], ['torres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apartamentos',
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('estado', sa.Enum('disponible', 'reservado', 'vendido', name='estadoapartamento'), nullable=True),
    sa.Column('tipo_id', sa.UUID(), nullable=True),
    sa.Column('piso_id', sa.UUID(), nullable=True),
    sa.Column('asesor_id', sa.UUID(), nullable=True),
    sa.Column('comprador_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asesor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['comprador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['piso_id'], ['pisos.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipos_plantilla.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apartamentos')
    op.drop_table('pisos')
    op.drop_table('torres')
    op.drop_table('proyectos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('tipos_plantilla')
    # ### end Alembic commands ###
