"""Add tipo_inmueble to Proyectos

Revision ID: 206f47b901bb
Revises: adaffcf1a2c1
Create Date: 2026-02-24 23:34:02.567805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '206f47b901bb'
down_revision: Union[str, None] = 'adaffcf1a2c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyectos', sa.Column('tipo_inmueble', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proyectos', 'tipo_inmueble')
    # ### end Alembic commands ###
