"""Change zona_social to JSON

Revision ID: 22fd87072151
Revises: afc6bad271d4
Create Date: 2026-02-28 17:37:27.206675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22fd87072151'
down_revision: Union[str, None] = 'afc6bad271d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pisos', 'zona_social',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='zona_social::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pisos', 'zona_social',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='zona_social::varchar')
    # ### end Alembic commands ###
