"""Add zona_social to Piso

Revision ID: 4e93460704d7
Revises: ceaef9f9f5ab
Create Date: 2026-02-27 12:17:00.293332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e93460704d7'
down_revision: Union[str, None] = 'ceaef9f9f5ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pisos', sa.Column('zona_social', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pisos', 'zona_social')
    # ### end Alembic commands ###
