"""Add imagen_url to TipoPlantilla

Revision ID: 5d894b8c00e1
Revises: 8d9cf89bcc66
Create Date: 2026-03-08 19:24:29.544566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d894b8c00e1'
down_revision: Union[str, None] = '8d9cf89bcc66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipos_plantilla', sa.Column('imagen_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipos_plantilla', 'imagen_url')
    # ### end Alembic commands ###
