"""Add Empleado model

Revision ID: 858cb3bd6a96
Revises: 22fd87072151
Create Date: 2026-02-28 20:25:41.985233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '858cb3bd6a96'
down_revision: Union[str, None] = '22fd87072151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleados',
    sa.Column('nombre_completo', sa.String(), nullable=False),
    sa.Column('documento_identidad', sa.String(), nullable=True),
    sa.Column('cargo', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('fecha_contratacion', sa.DateTime(), nullable=True),
    sa.Column('salario', sa.Float(), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'inactivo', name='estadoempleado'), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empleados')
    # ### end Alembic commands ###
