"""Add ZonaSocialOpcion

Revision ID: 8d9cf89bcc66
Revises: 1ac7fc54f1ae
Create Date: 2026-03-06 12:10:23.826935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d9cf89bcc66'
down_revision: Union[str, None] = '1ac7fc54f1ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zona_social_opcion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zona_social_opcion')
    # ### end Alembic commands ###
