"""Add proyecto_id to TipoPlantilla

Revision ID: adaffcf1a2c1
Revises: b73c558ea786
Create Date: 2026-02-24 11:59:47.988627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adaffcf1a2c1'
down_revision: Union[str, None] = 'b73c558ea786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipos_plantilla', sa.Column('proyecto_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tipos_plantilla', 'proyectos', ['proyecto_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tipos_plantilla', type_='foreignkey')
    op.drop_column('tipos_plantilla', 'proyecto_id')
    # ### end Alembic commands ###
