"""Add imagen_url to proyectos

Revision ID: afc6bad271d4
Revises: 4e93460704d7
Create Date: 2026-02-27 12:55:17.050781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afc6bad271d4'
down_revision: Union[str, None] = '4e93460704d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyectos', sa.Column('imagen_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proyectos', 'imagen_url')
    # ### end Alembic commands ###
