"""Extract Comprador entity

Revision ID: b73c558ea786
Revises: 1be94bebf9c4
Create Date: 2026-02-24 00:09:12.417723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b73c558ea786'
down_revision: Union[str, None] = '1be94bebf9c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compradores',
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('entidad_financiera', sa.String(), nullable=True),
    sa.Column('estado_credito', postgresql.ENUM('preaprobado', 'aprobado', 'definitivo', name='estadocredito', create_type=False), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compradores_email'), 'compradores', ['email'], unique=True)
    op.drop_constraint('apartamentos_comprador_id_fkey', 'apartamentos', type_='foreignkey')
    op.create_foreign_key(None, 'apartamentos', 'compradores', ['comprador_id'], ['id'])
    op.drop_column('usuarios', 'estado_credito')
    op.drop_column('usuarios', 'entidad_financiera')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('entidad_financiera', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('usuarios', sa.Column('estado_credito', postgresql.ENUM('preaprobado', 'aprobado', 'definitivo', name='estadocredito'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'apartamentos', type_='foreignkey')
    op.create_foreign_key('apartamentos_comprador_id_fkey', 'apartamentos', 'usuarios', ['comprador_id'], ['id'])
    op.drop_index(op.f('ix_compradores_email'), table_name='compradores')
    op.drop_table('compradores')
    # ### end Alembic commands ###
