"""Split ubicacion into departamento and ciudad

Revision ID: ceaef9f9f5ab
Revises: 206f47b901bb
Create Date: 2026-02-24 23:48:02.599581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceaef9f9f5ab'
down_revision: Union[str, None] = '206f47b901bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyectos', sa.Column('departamento', sa.String(), nullable=True))
    op.add_column('proyectos', sa.Column('ciudad', sa.String(), nullable=True))
    op.drop_column('proyectos', 'ubicacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proyectos', sa.Column('ubicacion', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('proyectos', 'ciudad')
    op.drop_column('proyectos', 'departamento')
    # ### end Alembic commands ###
